.pragma library

var data = {
    "enabled": true,
    "position": "top",
    "launcherIcon": "",
    "launcherIconTint": true,
    "launcherIconFullTint": true,
    "launcherIconSize": 18,
    "screenList": [],
    "enableFirefoxPlayer": false,
    "playerTitleIntroMs": 2800,
    "barColor": [["primary", 0.22]],
    "height": 40,
    "width": 0,
    "padding": 2,
    "margin": 0,
    "spacing": 4,
    "radius": 16,
    "backgroundOpacity": 0.92,
    "pinnedOnStartup": true,
    "hoverToReveal": true,
    "hoverRegionHeight": 8,
    "showPinButton": true,
    "availableOnFullscreen": false,
    "clockFormat": "12h",
    "showWorkspaceModule": true,
    "showUptimeModule": true,
    "showMonitorModule": true,
    "showBatteryModule": true,
    "showNotificationsModule": true,
    "showNetworkModule": true,
    "showTrayModule": true,
    "showBluetoothModule": true,
    "showVolumeModule": true,
    "showBrightnessModule": true,
    "showPowerModule": true
}
