# Asura Foot terminal theme

include=~/.config/foot/themes/noctalia

term=foot
login-shell=yes
app-id=foot
title=foot
font=JetBrainsMono Nerd Font:size=11
dpi-aware=no
initial-color-theme=dark
initial-window-size-chars=92x27
pad=12x10
resize-by-cells=yes
bold-text-in-bright=yes

[scrollback]
lines=8000
multiplier=3.5
indicator-position=relative

[cursor]
style=block
blink=no
beam-thickness=1.8

[mouse]
hide-when-typing=no
alternate-scroll-mode=yes

[colors-dark]
alpha=0.94
background=150f12
foreground=f5e9ec
flash=ff6f91
flash-alpha=0.35
cursor=150f12 ff8b3d
selection-foreground=150f12
selection-background=f4b8d8
urls=9ee7e3

regular0=24191d
regular1=ff5c7a
regular2=8bd88b
regular3=f5c96f
regular4=8ec7ff
regular5=d98cff
regular6=73e7dc
regular7=f5e9ec

bright0=6e5961
bright1=ff7d99
bright2=a6eea6
bright3=ffd98a
bright4=a9d6ff
bright5=e7a8ff
bright6=9ef2ea
bright7=ffffff

[csd]
preferred=server
size=30
color=f5e9ec
button-width=30
button-color=150f12
button-minimize-color=8ec7ff
button-maximize-color=8bd88b
button-close-color=ff5c7a

[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0
