# Shared Home Manager module: Hyprland compositor defaults used by all Asura hosts.
{
  pkgs,
  lib,
  ...
}:
let
  border-size = 1;
  gaps-in = 4;
  gaps-out = 8;
  active-opacity = 1.0;
  inactive-opacity = 1.0;
  rounding = 10;
  blur = false;
  keyboardLayout = "us";
  border-color = "rgb(b4befe)";

  filePickerTitle = "^(.*(Open File|Open Folder|Choose Files|Choose Folder|File Upload|Save As|Select.*(File|Folder|Directory|extension directory)|Browse.*(File|Folder|Directory)|Library).*)$";

  startupCommands = [
    "dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP XDG_SESSION_TYPE XDG_SESSION_CLASS XDG_SESSION_ID XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS"
    "systemctl --user start skwd-daemon.service"
    "asura-apply-cursor-theme"
    "asura-monitor-guard --daemon"
    "asura-shell-switch autostart"
    "systemctl --user start hyprpolkitagent"
  ];
in
{
  imports = [
    ./animations.nix
    ./bindings.nix
    ./hyprlock.nix
    ./polkitagent.nix
    ./hypridle.nix
  ];

  home.packages = with pkgs; [
    brightnessctl
    libva
    qt6.qtwayland
    wayland-utils
  ];

  wayland.windowManager.hyprland = {
    enable = true;
    configType = "hyprlang";
    package = pkgs.hyprland;
    portalPackage = null;
    plugins = [ ];
    xwayland.enable = true;
    systemd = {
      enable = true;
      enableXdgAutostart = true;
      variables = [
        "DISPLAY"
        "HYPRLAND_INSTANCE_SIGNATURE"
        "WAYLAND_DISPLAY"
        "XDG_CURRENT_DESKTOP"
        "XDG_SESSION_DESKTOP"
        "XDG_SESSION_TYPE"
        "XDG_SESSION_CLASS"
        "XDG_RUNTIME_DIR"
        "DBUS_SESSION_BUS_ADDRESS"
      ];
    };

    settings = {
      exec_once = startupCommands;

      cursor = {
        no_hardware_cursors = 2;
        inactive_timeout = 0;
        enable_hyprcursor = true;
        sync_gsettings_theme = true;
      };

      general = {
        resize_on_border = true;
        gaps_in = gaps-in;
        gaps_out = gaps-out;
        border_size = border-size;
        layout = "dwindle";
        "col.active_border" = border-color;
      };

      decoration = {
        active_opacity = active-opacity;
        inactive_opacity = inactive-opacity;
        rounding = rounding;
        "shadow:enabled" = false;
        blur = {
          enabled = blur;
          size = 3;
          passes = 1;
          new_optimizations = true;
        };
      };

      master = {
        new_status = "master";
        allow_small_split = true;
        mfact = 0.5;
      };

      dwindle = {
        force_split = 2;
        preserve_split = true;
        smart_split = false;
        smart_resizing = true;
      };

      debug = {
        vfr = true;
      };

      misc = {
        vrr = 1;
        animate_manual_resizes = false;
        animate_mouse_windowdragging = false;
        disable_hyprland_logo = true;
        disable_splash_rendering = true;
        force_default_wallpaper = 0;
        focus_on_activate = true;
        enable_swallow = false;
        swallow_regex = "";
      };

      render = {
        direct_scanout = 2;
        cm_auto_hdr = 1;
      };

      input = {
        kb_layout = keyboardLayout;
        kb_options = "caps:escape";
        follow_mouse = 1;
        sensitivity = 0.5;
        repeat_delay = 300;
        repeat_rate = 50;
        numlock_by_default = true;
        touchpad = {
          natural_scroll = true;
          tap_button_map = "lrm";
          clickfinger_behavior = false;
        };
      };

      env = [
        "XDG_SESSION_TYPE,wayland"
        "XDG_CURRENT_DESKTOP,Hyprland"
        "XDG_SESSION_DESKTOP,Hyprland"
        "XDG_SESSION_CLASS,user"
        "LANG,en_US.UTF-8"
        "MOZ_ENABLE_WAYLAND,1"
        "QT_QPA_PLATFORM,wayland;xcb"
        "QT_WAYLAND_DISABLE_WINDOWDECORATION,1"
        "ELECTRON_OZONE_PLATFORM_HINT,auto"
        "SDL_VIDEODRIVER,wayland,x11"
        "CLUTTER_BACKEND,wayland"
        "XCURSOR_SIZE,24"
        "XCURSOR_THEME,Bibata-Modern-Amber"
        "HYPRCURSOR_SIZE,24"
        "HYPRCURSOR_THEME,Bibata-Modern-Amber"
      ];

      gesture = [
        "3, horizontal, workspace"
        "4, horizontal, workspace"
      ];
    };

    extraConfig = "";
  };

  xdg.configFile."hypr/hyprland.conf".force = true;
  xdg.configFile."hypr/hyprland.conf".text = "# Hyprland 0.56.0 Lua configuration active at hyprland.lua\nautogenerated = 0\n";

  xdg.configFile."hypr/hyprland.lua".force = true;
  xdg.configFile."hypr/hyprland.lua".text = ''
    -- Hyprland 0.56.0 Lua Configuration
    -- Declaratively generated by NixOS Home Manager for Asura

    -- Curves (Beziers)
    hl.curve("linear", { type = "bezier", points = { {0, 0}, {1, 1} } })
    hl.curve("md3_standard", { type = "bezier", points = { {0.2, 0}, {0, 1} } })
    hl.curve("md3_decel", { type = "bezier", points = { {0.05, 0.7}, {0.1, 1} } })
    hl.curve("md3_accel", { type = "bezier", points = { {0.3, 0}, {0.8, 0.15} } })
    hl.curve("overshot", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.1} } })
    hl.curve("crazyshot", { type = "bezier", points = { {0.1, 1.5}, {0.76, 0.92} } })
    hl.curve("hyprnostretch", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.0} } })
    hl.curve("menu_decel", { type = "bezier", points = { {0.1, 1}, {0, 1} } })
    hl.curve("menu_accel", { type = "bezier", points = { {0.38, 0.04}, {1, 0.07} } })
    hl.curve("easeInOutCirc", { type = "bezier", points = { {0.85, 0}, {0.15, 1} } })
    hl.curve("easeOutCirc", { type = "bezier", points = { {0, 0.55}, {0.45, 1} } })
    hl.curve("easeOutExpo", { type = "bezier", points = { {0.16, 1}, {0.3, 1} } })
    hl.curve("softAcDecel", { type = "bezier", points = { {0.26, 0.26}, {0.15, 1} } })
    hl.curve("md2", { type = "bezier", points = { {0.4, 0}, {0.2, 1} } })

    -- Animations
    hl.animation("windows", { enabled = true, speed = 1, bezier = "md3_decel", style = "popin 60%" })
    hl.animation("windowsIn", { enabled = true, speed = 1, bezier = "md3_decel", style = "popin 60%" })
    hl.animation("windowsOut", { enabled = true, speed = 1, bezier = "md3_accel", style = "popin 60%" })
    hl.animation("border", { enabled = true, speed = 3, bezier = "default" })
    hl.animation("fade", { enabled = true, speed = 1, bezier = "md3_decel" })
    hl.animation("layersIn", { enabled = true, speed = 1, bezier = "menu_decel", style = "slide" })
    hl.animation("layersOut", { enabled = true, speed = 1, bezier = "menu_accel" })
    hl.animation("fadeLayersIn", { enabled = true, speed = 1, bezier = "menu_decel" })
    hl.animation("fadeLayersOut", { enabled = true, speed = 1, bezier = "menu_accel" })
    hl.animation("workspaces", { enabled = true, speed = 1, bezier = "menu_decel", style = "slide" })
    hl.animation("specialWorkspace", { enabled = true, speed = 1, bezier = "md3_decel", style = "slidevert" })

    -- Monitors (Full HD 1080p @ 144Hz, unscaled 1.0)
    hl.monitor("desc:eDP-1,1920x1080@144,0x0,1")
    hl.monitor("eDP-1,1920x1080@144,0x0,1")
    hl.monitor(",preferred,auto,1")

    -- General & Decoration Settings
    hl.config({
      general = {
        border_size = 1,
        ["col.active_border"] = "rgb(b4befe)",
        gaps_in = 4,
        gaps_out = 8,
        layout = "dwindle",
        resize_on_border = true,
      },
      decoration = {
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        rounding = 10,
        ["shadow:enabled"] = false,
        blur = {
          enabled = false,
          size = 3,
          passes = 1,
          new_optimizations = true,
        },
      },
      input = {
        kb_layout = "${keyboardLayout}",
        kb_options = "caps:escape",
        follow_mouse = 1,
        sensitivity = 0.5,
        repeat_delay = 300,
        repeat_rate = 50,
        numlock_by_default = true,
        touchpad = {
          natural_scroll = true,
          tap_button_map = "lrm",
          clickfinger_behavior = false,
        },
      },
      dwindle = {
        force_split = 2,
        preserve_split = true,
        smart_split = false,
        smart_resizing = true,
      },
      master = {
        new_status = "master",
        allow_small_split = true,
        mfact = 0.5,
      },
      misc = {
        vrr = 1,
        animate_manual_resizes = false,
        animate_mouse_windowdragging = false,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        force_default_wallpaper = 0,
        focus_on_activate = true,
        enable_swallow = false,
        swallow_regex = "",
      },
      render = {
        direct_scanout = 2,
        cm_auto_hdr = 1,
      },
      cursor = {
        no_hardware_cursors = 2,
        inactive_timeout = 0,
        enable_hyprcursor = true,
        sync_gsettings_theme = true,
        default_monitor = "eDP-1",
      },
      debug = {
        vfr = true,
      },
    })

    -- Environment Variables
    hl.env("XDG_SESSION_TYPE,wayland")
    hl.env("XDG_CURRENT_DESKTOP,Hyprland")
    hl.env("XDG_SESSION_DESKTOP,Hyprland")
    hl.env("XDG_SESSION_CLASS,user")
    hl.env("LANG,en_US.UTF-8")
    hl.env("MOZ_ENABLE_WAYLAND,1")
    hl.env("QT_QPA_PLATFORM,wayland;xcb")
    hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION,1")
    hl.env("ELECTRON_OZONE_PLATFORM_HINT,auto")
    hl.env("SDL_VIDEODRIVER,wayland,x11")
    hl.env("CLUTTER_BACKEND,wayland")
    hl.env("XCURSOR_SIZE,24")
    hl.env("XCURSOR_THEME,Bibata-Modern-Amber")
    hl.env("HYPRCURSOR_SIZE,24")
    hl.env("HYPRCURSOR_THEME,Bibata-Modern-Amber")

    -- Startup Commands
    hl.exec_cmd("dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP XDG_SESSION_TYPE XDG_SESSION_CLASS XDG_SESSION_ID XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS")
    hl.exec_cmd("systemctl --user start skwd-daemon.service")
    hl.exec_cmd("asura-apply-cursor-theme")
    hl.exec_cmd("asura-monitor-guard --daemon")
    hl.exec_cmd("asura-shell-switch autostart")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")

    -- Keybindings (Hyprland 0.56.0 Native Lua Dispatcher Objects)
    hl.bind("SUPER", "Q", hl.dsp.window.close())
    hl.bind("SUPER", "H", hl.dsp.exit())
    hl.bind("SUPER", "F", hl.dsp.exec_cmd("asura-file-manager \"$HOME\""))
    hl.bind("SUPER", "G", hl.dsp.window.float())
    hl.bind("SUPER", "J", hl.dsp.layout("togglesplit"))
    hl.bind("SUPER", "B", hl.dsp.exec_cmd("${pkgs.brave}/bin/brave"))
    hl.bind("SUPER", "T", hl.dsp.exec_cmd("${pkgs.foot}/bin/foot"))
    hl.bind("SUPER", "C", hl.dsp.exec_cmd("code --ozone-platform=wayland"))
    hl.bind("SUPER", "E", hl.dsp.exec_cmd("${pkgs.telegram-desktop}/bin/telegram-desktop"))
    hl.bind("SUPER", "W", hl.dsp.exec_cmd("skwd-wall"))
    hl.bind("SUPER", "P", hl.dsp.exec_cmd("asura-display-manager"))
    hl.bind("SUPER+SHIFT", "P", hl.dsp.exec_cmd("asura-monitor-guard --restore"))
    hl.bind("CTRL", "L", hl.dsp.exec_cmd("/run/current-system/sw/bin/asura-session-lock"))
    hl.bind("SUPER", "L", hl.dsp.exec_cmd("/run/current-system/sw/bin/asura-session-lock"))
    hl.bind("SUPER", "V", hl.dsp.exec_cmd("asura-shell-launcher /clipboard"))
    hl.bind("SUPER+SHIFT", "V", hl.dsp.window.float())
    hl.bind("SUPER+SHIFT", "C", hl.dsp.exec_cmd("asura-shell-launcher /clipboard"))
    hl.bind("SUPER+SHIFT", "E", hl.dsp.exec_cmd("asura-shell-launcher /emo"))
    hl.bind("SUPER+SHIFT", "S", hl.dsp.exec_cmd("asura-screenshot region"))
    hl.bind("SUPER+SHIFT", "W", hl.dsp.exec_cmd("skwd-wall"))
    hl.bind("SUPER+SHIFT", "R", hl.dsp.exec_cmd("asura-screen-record-toggle"))
    hl.bind("SUPER+SHIFT", "X", hl.dsp.exec_cmd("asura-screenshot region-edit"))
    hl.bind("SUPER", "F2", hl.dsp.exec_cmd("night-shift"))
    hl.bind("SUPER", "N", hl.dsp.exec_cmd("asura-shell-launcher /notes"))
    hl.bind("SUPER", "D", hl.dsp.exec_cmd("asura-shell-launcher /dashboard"))
    hl.bind("SUPER", "S", hl.dsp.exec_cmd("asura-shell-launcher /config"))
    hl.bind("CTRL+ALT", "Delete", hl.dsp.exec_cmd("asura-shell-launcher /session"))
    hl.bind("SUPER", "BackSpace", hl.dsp.exec_cmd("asura-shell-launcher /session"))
    hl.bind("SUPER", "Period", hl.dsp.exec_cmd("asura-shell-launcher /emo"))
    hl.bind("CTRL+SUPER", "R", hl.dsp.exec_cmd("asura-shell-switch reload"))
    hl.bind("", "Print", hl.dsp.exec_cmd("asura-screenshot full"))
    hl.bind("SHIFT", "Print", hl.dsp.exec_cmd("asura-screenshot region"))
    hl.bind("SUPER", "Print", hl.dsp.exec_cmd("asura-screenshot output"))
    hl.bind("SUPER+SHIFT", "Print", hl.dsp.exec_cmd("asura-screenshot region-edit"))
    hl.bind("SUPER", "left", hl.dsp.exec_cmd("movefocus l"))
    hl.bind("SUPER", "right", hl.dsp.exec_cmd("movefocus r"))
    hl.bind("SUPER", "up", hl.dsp.exec_cmd("movefocus u"))
    hl.bind("SUPER", "down", hl.dsp.exec_cmd("movefocus d"))
    hl.bind("ALT", "Tab", hl.dsp.exec_cmd("asura-shell-launcher /overview"))
    hl.bind("ALT+SHIFT", "Tab", hl.dsp.window.cycle_next({ prev = true }))
    hl.bind("SUPER", "Tab", hl.dsp.window.cycle_next())

    -- Workspaces 1..10
    hl.bind("SUPER", "1", hl.dsp.exec_cmd("workspace 1"))
    hl.bind("SUPER+SHIFT", "1", hl.dsp.exec_cmd("movetoworkspace 1"))
    hl.bind("SUPER", "2", hl.dsp.exec_cmd("workspace 2"))
    hl.bind("SUPER+SHIFT", "2", hl.dsp.exec_cmd("movetoworkspace 2"))
    hl.bind("SUPER", "3", hl.dsp.exec_cmd("workspace 3"))
    hl.bind("SUPER+SHIFT", "3", hl.dsp.exec_cmd("movetoworkspace 3"))
    hl.bind("SUPER", "4", hl.dsp.exec_cmd("workspace 4"))
    hl.bind("SUPER+SHIFT", "4", hl.dsp.exec_cmd("movetoworkspace 4"))
    hl.bind("SUPER", "5", hl.dsp.exec_cmd("workspace 5"))
    hl.bind("SUPER+SHIFT", "5", hl.dsp.exec_cmd("movetoworkspace 5"))
    hl.bind("SUPER", "6", hl.dsp.exec_cmd("workspace 6"))
    hl.bind("SUPER+SHIFT", "6", hl.dsp.exec_cmd("movetoworkspace 6"))
    hl.bind("SUPER", "7", hl.dsp.exec_cmd("workspace 7"))
    hl.bind("SUPER+SHIFT", "7", hl.dsp.exec_cmd("movetoworkspace 7"))
    hl.bind("SUPER", "8", hl.dsp.exec_cmd("workspace 8"))
    hl.bind("SUPER+SHIFT", "8", hl.dsp.exec_cmd("movetoworkspace 8"))
    hl.bind("SUPER", "9", hl.dsp.exec_cmd("workspace 9"))
    hl.bind("SUPER+SHIFT", "9", hl.dsp.exec_cmd("movetoworkspace 9"))
    hl.bind("SUPER", "0", hl.dsp.exec_cmd("workspace 10"))
    hl.bind("SUPER+SHIFT", "0", hl.dsp.exec_cmd("movetoworkspace 10"))

    -- Mouse Binds
    hl.bind("SUPER", "mouse:272", hl.dsp.exec_cmd("movewindow"), { mouse = true })
    hl.bind("SUPER", "mouse:273", hl.dsp.exec_cmd("resizewindow"), { mouse = true })

    -- Release Binds
    hl.bind("SUPER", "SUPER_L", hl.dsp.exec_cmd("asura-shell-launcher"), { release = true })
    hl.bind("SUPER", "SUPER_R", hl.dsp.exec_cmd("asura-shell-launcher"), { release = true })

    -- Media & Hardware Key Binds
    hl.bind("", "XF86AudioMute", hl.dsp.exec_cmd("sound-toggle"), { locked = true })
    hl.bind("", "XF86AudioPlay", hl.dsp.exec_cmd("${pkgs.playerctl}/bin/playerctl play-pause"), { locked = true })
    hl.bind("", "XF86AudioNext", hl.dsp.exec_cmd("${pkgs.playerctl}/bin/playerctl next"), { locked = true })
    hl.bind("", "XF86AudioPrev", hl.dsp.exec_cmd("${pkgs.playerctl}/bin/playerctl previous"), { locked = true })
    hl.bind("", "switch:Lid Switch", hl.dsp.exec_cmd("/run/current-system/sw/bin/asura-session-lock"), { locked = true })
    hl.bind("", "F3", hl.dsp.exec_cmd("sound-toggle"), { locked = true })
    hl.bind("", "F5", hl.dsp.exec_cmd("sound-down"), { locked = true })
    hl.bind("", "F6", hl.dsp.exec_cmd("sound-up"), { locked = true })
    hl.bind("", "F8", hl.dsp.exec_cmd("brightness-down"), { locked = true })
    hl.bind("", "F9", hl.dsp.exec_cmd("brightness-up"), { locked = true })
    hl.bind("", "F10", hl.dsp.exec_cmd("asura-camera-app"), { locked = true })
    hl.bind("", "F11", hl.dsp.exec_cmd("asura-airplane-toggle"), { locked = true })
    hl.bind("", "F12", hl.dsp.exec_cmd("night-shift"), { locked = true })

    hl.bind("", "XF86AudioRaiseVolume", hl.dsp.exec_cmd("sound-up"), { locked = true, ["repeat"] = true })
    hl.bind("", "XF86AudioLowerVolume", hl.dsp.exec_cmd("sound-down"), { locked = true, ["repeat"] = true })
    hl.bind("", "XF86MonBrightnessUp", hl.dsp.exec_cmd("brightness-up"), { locked = true, ["repeat"] = true })
    hl.bind("", "XF86MonBrightnessDown", hl.dsp.exec_cmd("brightness-down"), { locked = true, ["repeat"] = true })

    -- Submaps
    hl.define_submap("resize", function()
      hl.bind("", "right", hl.dsp.exec_cmd("resizeactive 30 0"), { ["repeat"] = true })
      hl.bind("", "left", hl.dsp.exec_cmd("resizeactive -30 0"), { ["repeat"] = true })
      hl.bind("", "up", hl.dsp.exec_cmd("resizeactive 0 -30"), { ["repeat"] = true })
      hl.bind("", "down", hl.dsp.exec_cmd("resizeactive 0 30"), { ["repeat"] = true })
      hl.bind("", "escape", hl.dsp.exec_cmd("submap reset"))
      hl.bind("SUPER+SHIFT", "Tab", hl.dsp.exec_cmd("submap reset"))
    end)

    -- Gestures
    hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
    hl.gesture({ fingers = 4, direction = "horizontal", action = "workspace" })
  '';
}
