[audio]
enable_sounds = false

[bar]
order = [ "dynamic_island" ]

    [bar.customized]
    auto_hide = false
    background_opacity = 1.0
    capsule = false
    center = []
    enabled = false
    end = [ "battery", "volume", "network", "notifications", "clipboard", "session" ]
    layer = "overlay"
    margin_edge = 8
    margin_ends = 16
    padding = 10
    radius = 19
    scale = 1.0
    shadow = false
    start = [ "launcher", "clock", "active_window", "workspaces" ]
    thickness = 38
    widget_spacing = 6

        [[bar.customized.capsule_group]]
        border = "outline"
        fill = "surface_variant"
        id = "start_group"
        members = [ "launcher", "clock", "active_window" ]
        opacity = 1.0
        radius = 8.0

        [[bar.customized.capsule_group]]
        border = "outline"
        fill = "surface_variant"
        id = "workspaces_group"
        members = [ "workspaces" ]
        opacity = 1.0
        radius = 8.0

        [[bar.customized.capsule_group]]
        border = "outline"
        fill = "surface_variant"
        id = "end_group"
        members = [ "battery", "volume", "network", "notifications", "clipboard", "session" ]
        opacity = 1.0
        radius = 8.0

    [bar.default]
    center = [ "clock" ]
    enabled = false
    end = [ "tray", "network", "volume", "brightness", "battery", "session" ]
    margin_edge = 1
    start = [ "launcher", "control-center", "workspaces" ]

    [bar.dynamic_island]
    auto_hide = false
    background_opacity = 1.0
    capsule = false
    center = [ "clock" ]
    end = [ "volume", "battery", "session" ]
    margin_edge = 0
    margin_ends = 427
    padding = 10
    position = "top"
    radius_bottom_left = 19
    radius_bottom_right = 19
    radius_top_left = 0
    radius_top_right = 0
    reserve_space = true
    scale = 1.0
    shadow = false
    start = [ "workspaces" ]
    thickness = 38
    widget_spacing = 8

    [bar.left_bar]
    auto_hide = true
    background_opacity = 0.88
    capsule = false
    center = [ "screenshot_btn", "open_screenshots_btn", "record_btn", "record_pause_btn", "record_status_btn", "open_recordings_btn", "google_lens_btn" ]
    end = []
    margin_edge = 8
    margin_ends = 400
    padding = 8
    position = "left"
    radius = 16
    reserve_space = false
    scale = 1.0
    shadow = false
    start = []
    thickness = 48
    widget_spacing = 20

[calendar]
enabled = true

[desktop_widgets]
enabled = false

[dock]
auto_hide = true
enabled = false
icon_size = 35
active_scale = 1.0
background_opacity = 0.82
cross_axis_padding = 6
inactive_scale = 1.0
item_spacing = 3
magnification = false
main_axis_padding = 10
radius = 10
reserve_space = false
shadow = false
show_dots = true

[location]
address = "rishikesh, India"
auto_locate = false

[lockscreen]
blur_intensity = 0.0
blurred_desktop = false
tint_intensity = 0.15
wallpaper = "/etc/nixos/assets/she.jpg"

[lockscreen_widgets]
enabled = false
schema_version = 1
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    cx = 960.0
    cy = 957.0
    output = "HDMI-A-1"
    rotation = 0.0
    scale = 1.0
    type = "login_box"

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    cx = 960.0
    cy = 957.0
    output = "eDP-1"
    rotation = 0.0
    scale = 1.0
    type = "login_box"

[nightlight]
enabled = true

[shell]
avatar_path = "/home/asura/Downloads/kyahua.png"
clipboard_enabled = false
clipboard_history_max_entries = 20
font_family = "JetBrainsMono Nerd Font"
lang = "en"
screen_time_enabled = false
settings_show_advanced = true
setup_wizard_enabled = false
show_location = false
telemetry_enabled = false
time_format = "{:%I:%M %p}"
ui_scale = 1.0500000081956387

    [shell.animation]
    enabled = false

    [shell.panel]
    control_center_placement = "attached"
    launcher_placement = "attached"
    open_near_click_control_center = false
    open_near_click_launcher = false
    session_placement = "attached"
    shadow = false
    wallpaper_placement = "floating"

    [shell.screen_corners]
    enabled = false
    size = 22

    [[shell.session.actions]]
    action = "lock"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = ""
    variant = "ghost"

    [[shell.session.actions]]
    action = "suspend"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = ""
    variant = "ghost"

    [[shell.session.actions]]
    action = "logout"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = ""
    variant = "ghost"

    [[shell.session.actions]]
    action = "reboot"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = ""
    variant = "ghost"

    [[shell.session.actions]]
    action = "shutdown"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = ""
    variant = "ghost"

    [[shell.session.actions]]
    action = "reboot"
    command = "systemctl reboot --firmware-setup"
    enabled = true
    glyph = "skull"
    label = "Firmware Boot"
    shortcut = ""
    variant = "ghost"

[system.monitor]
cpu_poll_seconds = 5.0
disk_poll_seconds = 30.0
enabled = true
gpu_poll_seconds = 0.0
memory_poll_seconds = 5.0
network_poll_seconds = 8.0

[theme]
builtin = "Kanagawa"
community_palette = "Vesper"
custom_palette = "Cherry Blossom"
mode = "dark"
source = "community"
wallpaper_scheme = "muted"

    [theme.templates]
    builtin_ids = [ "hyprland" ]

[wallpaper]
directory = "/home/asura/Wallpaper"
enabled = false
transition_duration = 0.0

    [wallpaper.default]
    path = "/home/asura/Wallpaper/random_wallpaper.jpg"

    [wallpaper.last]
    path = "/home/asura/Wallpaper/random_wallpaper.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/asura/Wallpaper/random_wallpaper.jpg"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/asura/Wallpaper/MXBpbZp.png"
    theme_mode = "dark"
    wallpaper_scheme = "Monochrome"

    [[wallpaper.favorite]]
    path = "/home/asura/Wallpaper/1004017-colorized.png"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    community_palette = "Kanagawa Paper"
    palette_source = "community"
    path = "/home/asura/Wallpaper/138032536_p0.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    community_palette = "Vesper"
    palette_source = "community"
    path = "/home/asura/Wallpaper/Angel1.png"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    path = "/home/asura/Wallpaper/wallhaven-1qxxkg.png"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/asura/Wallpaper/wallhaven-211xrg.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "Ayu"

[widget.audio_visualizer]
type = "audio_visualizer"

[widget.bongocat]
audio_spectrum = true
script = "scripts/bongocat.lua"
tappy_mode = true
type = "scripted"

[widget.clock]
format = "{:%I:%M %p %a, %b %d}"

[widget.cpu]
stat = "cpu_usage"
type = "sysmon"

[widget.disk]
path = "/"
stat = "disk_pct"
type = "sysmon"

[widget.google_lens_btn]
command = "/home/asura/.local/bin/asura-lens-search"
glyph = "brand-google"
scale = 1.3500000000000001
tooltip = "Search Area on Google"
type = "custom_button"

[widget.keyboard_layout]
type = "keyboard_layout"

[widget.open_recordings_btn]
command = "xdg-open /home/asura/Videos/Screenrecords"
glyph = "folder"
scale = 1.3500000000000001
tooltip = "Open Recordings Folder"
type = "custom_button"

[widget.open_screenshots_btn]
command = "xdg-open /home/asura/Pictures/Screenshots"
glyph = "folder-open"
scale = 1.3500000000000001
tooltip = "Open Screenshots Folder"
type = "custom_button"

[widget.ram]
stat = "ram_pct"
type = "sysmon"

[weather]
effects = false
enabled = false

[widget.record_btn]
command = "/run/current-system/sw/bin/asura-screen-record-toggle"
glyph = "video"
scale = 1.3500000000000001
tooltip = "Toggle Screen Recording"
type = "custom_button"

[widget.record_pause_btn]
command = "/run/current-system/sw/bin/asura-screen-record-toggle toggle-pause"
glyph = "player-pause"
scale = 1.3500000000000001
tooltip = "Pause or Resume Recording"
type = "custom_button"

[widget.record_status_btn]
command = "/run/current-system/sw/bin/asura-screen-record-toggle status"
glyph = "clock"
scale = 1.3500000000000001
tooltip = "Recording Status"
type = "custom_button"

[widget.screenshot_btn]
command = "asura-screenshot region"
glyph = "camera"
scale = 1.3500000000000001
tooltip = "Take Region Screenshot"
type = "custom_button"

[widget.temp]
stat = "cpu_temp"
type = "sysmon"
